### ISSUE TITLE
Cannot load gem with bundler

### ISSUE THREAD

**Issue by parisyee** [taxamo/taxamo-ruby#1]
Hello Taxamo Team,

I am having trouble loading the taxamo gem with bundler. I have added: 

``` ruby
gem "taxamo", github: "taxamo/taxamo-ruby"
```

to the gemfile of both a rails project as well as a simple script and receive this error at require:

```
/Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/require_all-1.0.1/lib/require_all.rb:59:in `rescue in require_all': no such file to load -- lib/taxamo/models/* (LoadError)
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/require_all-1.0.1/lib/require_all.rb:43:in `require_all'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/taxamo-ruby-e6f4dd29e19a/lib/taxamo.rb:17:in `<top (required)>'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `require'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `each'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `block in require'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `each'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `require'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.9.4/lib/bundler.rb:134:in `require'
    from /Users/parisyee/workspace/vat_test/config/application.rb:16:in `<top (required)>'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:82:in `require'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:82:in `preload'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:143:in `serve'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:131:in `block in run'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:125:in `loop'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:125:in `run'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/parisyee/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'
```

I know that in your readme you instruct to install via:

``` bash
gem install taxamo-1.0.1.gem
```

However this does not work for me - I receive: 

```
ERROR:  Could not find a valid gem 'taxamo-1.0.1.gem' (>= 0) in any repository
```

Thanks!

**Comment by tlipski** [comment]
Thanks for the report, I am looking into bundler issue. 

Is the command gem install ran from a directory containing cloned http://github.com/taxamo/taxamo-ruby repo?

**Comment by tlipski** [comment]
Please see if version `1.0.3` solves the issue for you.

**Comment by parisyee** [comment]
:clap: Thanks so much! Works great.

**Comment by tlipski** [comment]
Always happy to help and make the VATMESS at least a little easier here :)
