### ISSUE TITLE
How do we know when the transaction is declined by Taxamo?

### ISSUE THREAD

**Issue by bbozo** [taxamo/taxamo-ruby#3]
According to EU VAT rules, the transaction should not be processed unless there are two non-contradictory pieces of information to prove each buyer’s location (http://euvataction.org/key-facts/#key_applies),

since this part is done by Taxamo as far as I understand there should be an error scenario when the buyer's location can not be reliably calculated, only field in the API responses that could serve this is transaction status, but the API docs say that the only possible values are `N - new, C - confirmed, S - settled.`

So, how do we know when we aren't supposed to charge the customer and ask for further proof of location?

**Comment by tlipski** [comment]
Hi,

Taxamo will refuse to store such transaction:

```
irb(main):005:0> Taxamo.create_transaction({
irb(main):006:2*             'transaction' => {
irb(main):007:3*                 'currency_code' => 'USD',
irb(main):008:3*                 'buyer_ip' => '8.8.8.8',
irb(main):009:3*                 'billing_country_code' => 'IE',
irb(main):010:3*                 'order_date' => '2014-06-01',
irb(main):011:3*                 'buyer_email' => 'test-ruby@taxamo.com',
irb(main):012:3*                 'transaction_lines' => [{'amount' => 200,
irb(main):013:5*                                          'custom_id' => 'line1'},
irb(main):014:4*                                         {'amount' => 100,
irb(main):015:5*                                          'product_type' => 'e-book',
irb(main):016:5*                                          'custom_id' => 'line2'}]
irb(main):017:3>             }})
D, [2016-01-18T18:29:51.035975 #14906] DEBUG -- : https://api.taxamo.com/api/v1/transactions
ValidationError: ["Couldn't determine user's country based on provided details."]
    from /Users/tomek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/taxamo-1.0.5/lib/swagger/response.rb:23:in `initialize'
    from /Users/tomek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/taxamo-1.0.5/lib/swagger/request.rb:179:in `new'
    from /Users/tomek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/taxamo-1.0.5/lib/swagger/request.rb:179:in `make'
    from /Users/tomek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/taxamo-1.0.5/lib/taxamo.rb:258:in `create_transaction'
    from (irb):5
    from /Users/tomek/.rbenv/versions/2.2.1/bin/irb:11:in `<main>'
```

**Comment by tlipski** [comment]
Also, there is a Developer Guide, that might provide some assistance: https://www.taxamo.com/doc/dev_guide/ 

But if anything else is unclear, feel free to contact us at support@taxamo.com.
